### ISSUE TITLE
smart-pixel-react does not fire any events

### ISSUE THREAD

**Issue by botoxparty** [Webtrekk/Webtrekk-Smart-Pixel#4]
Hi,

Following the documentation, I cannot get the smart pixel to trigger any events using the react wrapper. I can trigger them manually from the console using `wtSmart`.

Here is a reproduction of the issue using Code sandbox. Maybe i've forgotten to initialise something?

https://codesandbox.io/s/webtrekk-not-working-3kg4n

**Comment by StephanGuenther** [comment]
We don't have a separate component for actions, you can only do this via **WebtrekkSmartPixelReact.action**.

Example:
```js
import { WebtrekkSmartPixelReact } from "@webtrekk-smart-pixel/react";

<button onClick={() => {
	WebtrekkSmartPixelReact.action({
		name: "en.click.on.some.link",
		parameter: {1: "en"},
		goal: {2: "goal value 2"}
	});
	WebtrekkSmartPixelReact.track();
}}>click</button>
```

**Comment by botoxparty** [comment]
So it seems that there's some issues with typings in the library, typescript detects WebtrekkSmartPixelReact as a type:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/24580068/117938741-a89df800-b307-11eb-8590-5f39aaa9f58f.png">

I can ignore the error and the track event is sent.

I am not looking to track actions, I am looking to track page views. How is this done? I have followed the documentation and it does not happen automatically. Not even the initial page view.

**Comment by StephanGuenther** [comment]
Use our WebtrekkAutoTracking components (see https://docs.mapp.com/display/WSPD/React#React-%3CWebtrekkAutoTracking%3E) or call **WebtrekkSmartPixelReact.track** in **componentDidMount** (see https://docs.mapp.com/display/WSPD/React#React-track).

**Comment by botoxparty** [comment]
Great thanks for the support, have got it running in the sandbox so can debug my environment.
