### ISSUE TITLE
WebtrekkSmartPixelModule missing type.d.ts 

### ISSUE THREAD

**Issue by nkrietenbrink** [Webtrekk/Webtrekk-Smart-Pixel#6]
Hey! I'm trying to use the Singlepage Solution of SmartPixel for Angular described here:
https://documentation.mapp.com/latest/en/angular-15741405.html

I have installed the package and trying to import WebtrekkSmartPixelModule inside the app.module.ts.

But i get an error:
TS7016: Could not find a declaration file for module '@webtrekk-smart-pixel/angular'. '/@webtrekk-smart-pixel/angular/index.js' implicitly has an 'any' type.

Seem like the types.d.ts is missing inside the package? Can anyone help me to fix it? Thanks!

**Comment by StephanGuenther** [comment]
We are currently working on it and will fix the issue as soon as possible.

**Comment by nkrietenbrink** [comment]
Could you give me some indication of when the fix will come? Or is there a temporary solution i could use to avoid this bug?

**Comment by StephanGuenther** [comment]
The new version will be published in the course of the next week.

**Comment by StephanGuenther** [comment]
The new version was released. Please use `npm install --save @webtrekk-smart-pixel/angular@2` for Angular v12+ and `npm install --save @webtrekk-smart-pixel/angular@1` for Angular v6 - v11.

**Comment by nkrietenbrink** [comment]
Perfect! The error is gone. Thank you!
